

services:
  app:
    image: $IMAGE_NAME
    platform: linux/amd64
    build:
      context: .
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://$DBHOST:$DBPORT/springbootsql?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true  
      - SPRING_DATASOURCE_USERNAME=$USERNAME
      - SPRING_DATASOURCE_PASSWORD=$ROOTPASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver 
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD
      - SPRING_MAIL_HOST=$SPRING_MAIL_HOST
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    container_name: $DBHOST
    environment:
      - POSTGRES_USER=$DBUSER
      - POSTGRES_PASSWORD=$ROOTPASSWORD
      - POSTGRES_DB=springbootsql
      - DB_USER=$DBUSER
      - DB_PASSWORD=$PASSWORD
      - H2_ENABLED=false
      - H2_PATH=/h2-console
      - ALLOW_OTHERS=false
    ports:
      - "$DBPORT:$DBPORT"