services:
  app:
    image: $IMAGE_NAME
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://$DBNAME:3306/springbootsql?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$USERNAME
      - SPRING_DATASOURCE_PASSWORD=$ROOTPASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - MYSQL_ROOT_PASSWORD=$ROOTPASSWORD
      - MYSQL_DATABASE=springbootsql
      - MYSQL_PASSWORD=$PASSWORD
      - SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD
      - SPRING_MAIL_HOST=$SPRING_MAIL_HOST
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: $DBNAME
    environment:
      - MYSQL_HOST=$DBNAME
      - MYSQL_USER=$DBUSER
      - MYSQL_PASSWORD=$PASSWORD
      - MYSQL_PORT=3306
      - DB_USER=$DBUSER
      - DB_PASSWORD=$PASSWORD
      - H2_ENABLED=false
      - H2_PATH=/h2-console
      - ALLOW_OTHERS=false
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql