version: '3.8'

services:
  app:
    image: spring-docker:0.0.1
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DBNAME}:3306/springbootsql?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - MYSQL_ROOT_PASSWORD=${ROOTPASSWORD}
      - MYSQL_DATABASE=springbootsql
      - MYSQL_PASSWORD=${PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_PORT=3306
      - DB_USER=dbuser
      - DB_PASSWORD=${PASSWORD}
      - H2_ENABLED=false
      - H2_PATH=/h2-console
      - ALLOW_OTHERS=false
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql