AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Java Spring Boot application on AWS Lambda'

Resources:
  SpringBootLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.testproductapi.springbootrelational.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ProxyResource:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: any
