package com.testproductapi.springbootrelational.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
//import jakarta.persistence.SequenceGenerator;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
//import lombok.NoArgsConstructor;

@Entity
// Lombok annotation to generate getters, setters, equals, hashCode, and toString methods
@Data
// Lombok annotation to generate a no-args constructor
//@NoArgsConstructor
// Lombok annotation to generate an all-args constructor
@AllArgsConstructor
// Lombok annotation to generate a builder pattern for creating instances
@Builder
// Specifies the name of the database table to which this entity is mapped
public class Product {
    
    @Id // PK
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "unique_product_seq")
    //@SequenceGenerator(name = "unique_user_seq", sequenceName = "db_seq_name", initialValue = 100, allocationSize = 5)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true) // make table column unique
    private String name;
    private String description;
    private double price;

    // all below generated by lombok

    // Constructors

    public Product(){}

    public Product(String name, String description, double price){
        // data gets mapped from the db
        this.name = name;
        this.description = description;
        this.price = price;
    }

    //getters, setters
    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    public void setDescription(String description){
        this.description = description;
    }
    public String getDescription(){
        return description;
    }

    public Double getPrice(){
        return price;
    }

    public void setPrice(Double price){
        this.price = price;
    }

    public Long getId(){
        return id;
    }

    public void setId(Long id){
        this.id = id;
    }
}
